<p>
    <?php echo e(__('When you open the game page the server generates a secret and a seed and reveals its hash (using HMAC SHA256 algorithm).')); ?>

    <?php echo e(__('The server secret represents randomly shuffled card deck.')); ?>

    <?php echo e(__('The server seed is a cryptographically secure random alpha-numeric string.')); ?>

    <?php echo e(__('The hash of these 2 strings helps to ensure that the initial card deck is not altered after you choose the bet amount.')); ?>

    <?php echo e(__('After the game is finished the server secret and the server seed are revealed, so you can easily calculate and verify the hash.')); ?>

</p>
<p>
    <?php echo e(__('When you play a game you can pass an extra custom string - client seed (if it\'s not specified a random number is automatically generated by your browser).')); ?>

    <?php echo e(__('The server will then calculate another hash using the server secret, the server seed and the client seed.')); ?>

    <?php echo e(__('The last 5 chars of this hash (representing a hexadecimal value) will be converted to an integer.')); ?>

    <?php echo e(__('The result number will be divided by 52 (number of cards in the deck) and N cards will be cut (moved from the top to the bottom of the deck), where N is the remainder of the division.')); ?>

    <?php echo e(__('Because the client seed can not be predicted by the server the number of cards cut from the initial deck is completely random and hence you can be sure that the game result is fair.')); ?>

</p>